package com.example.sharedkhatm

data class SurahInfo(
    val number: Int,
    val name: String,
    val type: String, // Mekki / Medeni
    val verseCount: Int
)

object SurahRepository {
    fun getAllSurahs(): List<SurahInfo> {
        return listOf(
            SurahInfo(1, "Fatiha", "Mekki", 7),
            SurahInfo(2, "Bakara", "Medeni", 286),
            SurahInfo(3, "Al-i İmran", "Medeni", 200),
            SurahInfo(4, "Nisa", "Medeni", 176),
            SurahInfo(5, "Maide", "Medeni", 120),
            SurahInfo(6, "En'am", "Mekki", 165),
            SurahInfo(7, "A'raf", "Mekki", 206),
            SurahInfo(8, "Enfal", "Medeni", 75),
            SurahInfo(9, "Tevbe", "Medeni", 129),
            SurahInfo(10, "Yunus", "Mekki", 109),
            SurahInfo(11, "Hud", "Mekki", 123),
            SurahInfo(12, "Yusuf", "Mekki", 111),
            SurahInfo(13, "Ra'd", "Medeni", 43),
            SurahInfo(14, "İbrahim", "Mekki", 52),
            SurahInfo(15, "Hicr", "Mekki", 99),
            SurahInfo(16, "Nahl", "Mekki", 128),
            SurahInfo(17, "İsra", "Mekki", 111),
            SurahInfo(18, "Kehf", "Mekki", 110),
            SurahInfo(19, "Meryem", "Mekki", 98),
            SurahInfo(20, "Taha", "Mekki", 135),
            SurahInfo(21, "Enbiya", "Mekki", 112),
            SurahInfo(22, "Hac", "Medeni", 78),
            SurahInfo(23, "Mü'minun", "Mekki", 118),
            SurahInfo(24, "Nur", "Medeni", 64),
            SurahInfo(25, "Furkan", "Mekki", 77),
            SurahInfo(26, "Şuara", "Mekki", 227),
            SurahInfo(27, "Neml", "Mekki", 93),
            SurahInfo(28, "Kasas", "Mekki", 88),
            SurahInfo(29, "Ankebut", "Mekki", 69),
            SurahInfo(30, "Rum", "Mekki", 60),
            SurahInfo(31, "Lokman", "Mekki", 34),
            SurahInfo(32, "Secde", "Mekki", 30),
            SurahInfo(33, "Ahzab", "Medeni", 73),
            SurahInfo(34, "Sebe", "Mekki", 54),
            SurahInfo(35, "Fatır", "Mekki", 45),
            SurahInfo(36, "Yasin-i Şerif", "Mekki", 83),
            SurahInfo(37, "Saffat", "Mekki", 182),
            SurahInfo(38, "Sad", "Mekki", 88),
            SurahInfo(39, "Zümer", "Mekki", 75),
            SurahInfo(40, "Mü'min", "Mekki", 85),
            SurahInfo(41, "Fussilet", "Mekki", 54),
            SurahInfo(42, "Şura", "Mekki", 53),
            SurahInfo(43, "Zuhruf", "Mekki", 89),
            SurahInfo(44, "Duhan", "Mekki", 59),
            SurahInfo(45, "Casiye", "Mekki", 37),
            SurahInfo(46, "Ahkaf", "Mekki", 35),
            SurahInfo(47, "Muhammed", "Medeni", 38),
            SurahInfo(48, "Fetih", "Medeni", 29),
            SurahInfo(49, "Hucurat", "Medeni", 18),
            SurahInfo(50, "Kaf", "Mekki", 45),
            SurahInfo(51, "Zariyat", "Mekki", 60),
            SurahInfo(52, "Tur", "Mekki", 49),
            SurahInfo(53, "Necm", "Mekki", 62),
            SurahInfo(54, "Kamer", "Mekki", 55),
            SurahInfo(55, "Rahman", "Medeni", 78),
            SurahInfo(56, "Vakıa", "Mekki", 96),
            SurahInfo(57, "Hadid", "Medeni", 29),
            SurahInfo(58, "Mücadele", "Medeni", 22),
            SurahInfo(59, "Haşr", "Medeni", 24),
            SurahInfo(60, "Mümtehine", "Medeni", 13),
            SurahInfo(61, "Saf", "Medeni", 14),
            SurahInfo(62, "Cuma", "Medeni", 11),
            SurahInfo(63, "Münafikun", "Medeni", 11),
            SurahInfo(64, "Tegabun", "Medeni", 18),
            SurahInfo(65, "Talak", "Medeni", 12),
            SurahInfo(66, "Tahrim", "Medeni", 12),
            SurahInfo(67, "Mülk", "Mekki", 30),
            SurahInfo(68, "Kalem", "Mekki", 52),
            SurahInfo(69, "Hakka", "Mekki", 52),
            SurahInfo(70, "Mearic", "Mekki", 44),
            SurahInfo(71, "Nuh", "Mekki", 28),
            SurahInfo(72, "Cin", "Mekki", 28),
            SurahInfo(73, "Müzzemmil", "Mekki", 20),
            SurahInfo(74, "Müddessir", "Mekki", 56),
            SurahInfo(75, "Kıyamet", "Mekki", 40),
            SurahInfo(76, "İnsan", "Medeni", 31),
            SurahInfo(77, "Mürselat", "Mekki", 50),
            SurahInfo(78, "Nebe", "Mekki", 40),
            SurahInfo(79, "Naziat", "Mekki", 46),
            SurahInfo(80, "Abese", "Mekki", 42),
            SurahInfo(81, "Tekvir", "Mekki", 29),
            SurahInfo(82, "İnfitar", "Mekki", 19),
            SurahInfo(83, "Mutaffifin", "Mekki", 36),
            SurahInfo(84, "İnşikak", "Mekki", 25),
            SurahInfo(85, "Bürüc", "Mekki", 22),
            SurahInfo(86, "Tarık", "Mekki", 17),
            SurahInfo(87, "A'la", "Mekki", 19),
            SurahInfo(88, "Gaşiye", "Mekki", 26),
            SurahInfo(89, "Fecr", "Mekki", 30),
            SurahInfo(90, "Beled", "Mekki", 20),
            SurahInfo(91, "Şems", "Mekki", 15),
            SurahInfo(92, "Leyl", "Mekki", 21),
            SurahInfo(93, "Duha", "Mekki", 11),
            SurahInfo(94, "İnşirah", "Mekki", 8),
            SurahInfo(95, "Tin", "Mekki", 8),
            SurahInfo(96, "Alak", "Mekki", 19),
            SurahInfo(97, "Kadir", "Mekki", 5),
            SurahInfo(98, "Beyyine", "Medeni", 8),
            SurahInfo(99, "Zilzal", "Medeni", 8),
            SurahInfo(100, "Adiyat", "Mekki", 11),
            SurahInfo(101, "Karia", "Mekki", 11),
            SurahInfo(102, "Tekasür", "Mekki", 8),
            SurahInfo(103, "Asr", "Mekki", 3),
            SurahInfo(104, "Hümeze", "Mekki", 9),
            SurahInfo(105, "Fil", "Mekki", 5),
            SurahInfo(106, "Kureyş", "Mekki", 4),
            SurahInfo(107, "Maun", "Mekki", 7),
            SurahInfo(108, "Kevser", "Mekki", 3),
            SurahInfo(109, "Kafirun", "Mekki", 6),
            SurahInfo(110, "Nasr", "Medeni", 3),
            SurahInfo(111, "Tebbet", "Mekki", 5),
            SurahInfo(112, "İhlas", "Mekki", 4),
            SurahInfo(113, "Felak", "Mekki", 5),
            SurahInfo(114, "Nas", "Mekki", 6)
        )
    }
}